package com.gorauskas.euler.solutions;

import com.gorauskas.euler.Euler;
import com.gorauskas.euler.Util;
import com.gorauskas.euler.streams.StreamUtil;

public class Euler12 implements Euler {

    @Override
    public double Solve() {
        return StreamUtil.triangleNumberSequence()
                .filter(x -> Util.numberOfDivisors(x) > 500)
                .findFirst()
                .getAsInt();
    }

    @Override
    public String getProblem() {
        return new StringBuilder()
                .append("Project Euler Problem 12:\n")
                .append("\n")
                .append("    The sequence of triangle numbers is generated by adding the natural \n")
                .append("    numbers. So the 7th triangle number would be \n")
                .append("    1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.\n")
                .append("\n")
                .append("    The first ten terms would be:\n")
                .append("\n")
                .append("    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...\n")
                .append("\n")
                .append("    Let us list the factors of the first seven triangle numbers:\n")
                .append("\n")
                .append("     1: 1\n")
                .append("     3: 1,3\n")
                .append("     6: 1,2,3,6\n")
                .append("    10: 1,2,5,10\n")
                .append("    15: 1,3,5,15\n")
                .append("    21: 1,3,7,21\n")
                .append("    28: 1,2,4,7,14,28\n")
                .append("\n")
                .append("    We can see that 28 is the first triangle number to have over five \n")
                .append("    divisors.\n")
                .append("\n")
                .append("    What is the value of the first triangle number to have over five hundred \n")
                .append("    divisors?\n")
                .toString();
    }

    @Override
    public String getAnswer() {
        return String.format("The first triangle number to have over 500 divisors is: %s"
                , (long)this.Solve());
    }
}
