package com.gorauskas.euler.solutions;

import com.gorauskas.euler.Euler;

import java.util.function.LongUnaryOperator;
import java.util.stream.Collectors;
import java.util.stream.LongStream;

public class Euler45 implements Euler {
    @Override
    public double Solve() {
        var tlist = LongStream.rangeClosed(1, 99999).map(x -> fnTri.applyAsLong(x)).boxed().collect(Collectors.toList());
        var pset = LongStream.rangeClosed(1, 99999).map(x -> fnPenta.applyAsLong(x)).boxed().collect(Collectors.toSet());
        var hset = LongStream.rangeClosed(1, 99999).map(x -> fnHex.applyAsLong(x)).boxed().collect(Collectors.toSet());

        for (var item : tlist) {
            if (pset.contains(item) && hset.contains(item)) {
                if (item > 40755) {
                    return item;
                }
            }
        }

        return 0;
    }

    @Override
    public String getProblem() {
        return new StringBuilder()
                .append("Project Euler Problem 45\n")
                .append("\n")
                .append("    Triangle, pentagonal, and hexagonal numbers are generated by the following\n")
                .append("    formulae:\n")
                .append("\n")
                .append("        Triangle    Tn=n(n+1)/2    1, 3, 6, 10, 15, ...\n")
                .append("        Pentagonal  Pn=n(3n−1)/2   1, 5, 12, 22, 35, ...\n")
                .append("        Hexagonal   Hn=n(2n−1)     1, 6, 15, 28, 45, ...\n")
                .append("\n")
                .append("    It can be verified that T285 = P165 = H143 = 40755.\n")
                .append("\n")
                .append("    Find the next triangle number that is also pentagonal and hexagonal.\n")
                .toString();
    }

    @Override
    public String getAnswer() {
        return String.format("The next triangle number that is also pentagonal and hexagonal is %s\n",
                (long)this.Solve());
    }

    private LongUnaryOperator fnTri = x -> x * (x + 1) / 2;
    private LongUnaryOperator fnPenta = x -> x * (3 * x - 1) / 2;
    private LongUnaryOperator fnHex = x -> x * (2 * x - 1);
}
